In [1]:
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")
df = titanic.loc[:,['age', 'fare']]

df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [2]:
def add_10(n):
    return n + 10

def add_two_obj(a,b):
    return a + b

print(add_10(10))
print(add_two_obj(10, 10))

20
20

In [3]:
sr1 = df['age'].apply(add_10)
sr1.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [4]:
sr2 = df['age'].apply(lambda n: n+10)
sr2.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [6]:
sr3 = df['age'].apply(add_two_obj, b=10)
sr3.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [7]:
sr4 = df['age'].apply(lambda a,b: a+b, b=10)
sr4.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [8]:
def over_thirty(age):
    return age>30

sr_map = df['age'].map(over_thirty)
sr_map.head()

0    False
1     True
2    False
3     True
4     True
Name: age, dtype: bool

In [9]:
sr_map2 = df['age'].map(lambda age: True if age > 30 else False)
sr_map2.head()

0    False
1     True
2    False
3     True
4     True
Name: age, dtype: bool

In [11]:
print(titanic['sex'].unique())
print('\n')
print(titanic['sex'].head())
print('\n')

over_forty_dict = {'male':0,'female':1}
titanic['gender'] = titanic['sex'].map(over_forty_dict)
print(titanic['gender'].head())

<StringArray>
['male', 'female']
Length: 2, dtype: str


0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: str


0    0
1    1
2    1
3    1
4    0
Name: gender, dtype: int64

In [12]:
df1 = df.map(add_10)
df1.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [13]:
df2 = df.map(lambda n : n+10)
df2.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [14]:
df3 = df.map(add_two_obj, b=10)
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [15]:
df4 = df.map(lambda a,b: a+b, b=10)
df4.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [16]:
def calculate_stats(col):

    max_val = col.max()
    min_val = col.min()
    mean_val = col.mean()
    median_val = col.median()

    return pd.Series([max_val, min_val, mean_val, median_val], index=['max', 'min', 'mean', 'median'])

result_df = df.apply(calculate_stats, axis=0)

result_df

              age        fare
max     80.000000  512.329200
min      0.420000    0.000000
mean    29.699118   32.204208
median  28.000000   14.454200

In [17]:
result_sr = df.apply(lambda x: x.max() - x.min(), axis=0)

result_sr

age      79.5800
fare    512.3292
dtype: float64

In [18]:
def calculate_diff_avg(row):
    diff = row.max() - row.min()
    avg = row.mean()
    return pd.Series([diff, avg], index=['차이', '평균'])

result_df2 = df.apply(calculate_diff_avg, axis=1)

result_df2

          차이        평균
0    14.7500  14.62500
1    33.2833  54.64165
2    18.0750  16.96250
3    18.1000  44.05000
4    26.9500  21.52500
..       ...       ...
886  14.0000  20.00000
887  11.0000  24.50000
888   0.0000  23.45000
889   4.0000  28.00000
890  24.2500  19.87500

[891 rows x 2 columns]

In [25]:
result_df3 = df.apply(lambda row, multiplier: pd.Series([row.max() - row.min() * multiplier, 
                                             row.mean()],index = ['차이', '평균']), 
                                             multiplier=2, axis=1)

result_df3

          차이        평균
0     7.5000  14.62500
1    -4.7167  54.64165
2    10.1500  16.96250
3   -16.9000  44.05000
4    18.9000  21.52500
..       ...       ...
886   1.0000  20.00000
887  -8.0000  24.50000
888 -23.4500  23.45000
889 -22.0000  28.00000
890  16.5000  19.87500

[891 rows x 2 columns]

In [26]:
filtered_columns = df.apply(lambda x: x.mean()>30)
print(filtered_columns, '\n')

filtered_df = df.loc[:, filtered_columns]
filtered_df

age     False
fare     True
dtype: bool

        fare
0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
..       ...
886  13.0000
887  30.0000
888  23.4500
889  30.0000
890   7.7500

[891 rows x 1 columns]

In [34]:
df['High'] = df.apply(lambda row: 'Yes' if row.mean() > 50 else 'No', axis=1)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [33]:
df

      age     fare High
0    22.0   7.2500   No
1    38.0  71.2833  Yes
2    26.0   7.9250   No
3    35.0  53.1000   No
4    35.0   8.0500   No
..    ...      ...  ...
886  27.0  13.0000   No
887  19.0  30.0000   No
888   NaN  23.4500   No
889  26.0  30.0000   No
890  32.0   7.7500   No

[891 rows x 3 columns]

In [35]:
df1 = titanic.loc[:,['age', 'fare']]
df2 = titanic.loc[:,['embark_town','embarked']]

def missing_value(df):
    return df.isnull()

result_df = df1.pipe(missing_value)
result_df

       age   fare
0    False  False
1    False  False
2    False  False
3    False  False
4    False  False
..     ...    ...
886  False  False
887  False  False
888   True  False
889  False  False
890  False  False

[891 rows x 2 columns]

In [36]:
def missing_count(df):
    return missing_value(df).sum()

result_series = df1.pipe(missing_count)
result_series

age     177
fare      0
dtype: int64

In [38]:
def total_number_missing(df):
    return missing_count(df).sum()

result_value = df1.pipe(total_number_missing)
print(result_value)

177

In [39]:
def extract_initial(df):
    df['town_initial'] = df['embark_town'].str[0]
    return df

def verify_initial(df):
    df['verified'] = df["embarked"] == df['town_initial']
    return df

verify_initial(extract_initial(df2))

     embark_town embarked town_initial  verified
0    Southampton        S            S      True
1      Cherbourg        C            C      True
2    Southampton        S            S      True
3    Southampton        S            S      True
4    Southampton        S            S      True
..           ...      ...          ...       ...
886  Southampton        S            S      True
887  Southampton        S            S      True
888  Southampton        S            S      True
889    Cherbourg        C            C      True
890   Queenstown        Q            Q      True

[891 rows x 4 columns]

In [41]:
embark_town = df2.pipe(extract_initial).pipe(verify_initial)
embark_town

     embark_town embarked town_initial  verified
0    Southampton        S            S      True
1      Cherbourg        C            C      True
2    Southampton        S            S      True
3    Southampton        S            S      True
4    Southampton        S            S      True
..           ...      ...          ...       ...
886  Southampton        S            S      True
887  Southampton        S            S      True
888  Southampton        S            S      True
889    Cherbourg        C            C      True
890   Queenstown        Q            Q      True

[891 rows x 4 columns]