In [1]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','sex',"class",'fare','survived']]

df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [2]:
grouped = df.groupby(['class'], observed=True)
print(grouped)

<pandas.api.typing.DataFrameGroupBy object at 0x000002A87F34BCB0>

In [3]:
for key, group in grouped:
    print("* key:", key)
    print("* number of data:", len(group))
    print(group.head())
    print('\n')

* key: ('First',)
* number of data: 216
     age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1


* key: ('Second',)
* number of data: 184
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1


* key: ('Third',)
* number of data: 491
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [4]:
average = grouped.mean(numeric_only=True)
average

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [6]:
group3 = grouped.get_group(('Third',))
group3.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [7]:
grouped_two = df.groupby(['class','sex'], observed=True)

for key, group in grouped_two:
    print("* key:", key)
    print("* number of data:", len(group))
    print(group.head())
    print('\n')

* key: ('First', 'female')
* number of data: 94
     age     sex  class      fare  survived
1   38.0  female  First   71.2833         1
3   35.0  female  First   53.1000         1
11  58.0  female  First   26.5500         1
31   NaN  female  First  146.5208         1
52  49.0  female  First   76.7292         1


* key: ('First', 'male')
* number of data: 122
     age   sex  class      fare  survived
6   54.0  male  First   51.8625         0
23  28.0  male  First   35.5000         1
27  19.0  male  First  263.0000         0
30  40.0  male  First   27.7208         0
34  28.0  male  First   82.1708         0


* key: ('Second', 'female')
* number of data: 76
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
41  27.0  female  Second  21.0000         0
43   3.0  female  Second  41.5792         1
53  29.0  female  Second  26.0000         1


* key: ('Second', 'male')
* number of data: 108
     age   sex   class  fare  survived
17   NaN  male  Second  13.0         1
20  35.0  male  Second  26.0         0
21  34.0  male  Second  13.0         1
33  66.0  male  Second  10.5         0
70  32.0  male  Second  10.5         0


* key: ('Third', 'female')
* number of data: 144
     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0


* key: ('Third', 'male')
* number of data: 347
     age   sex  class     fare  survived
0   22.0  male  Third   7.2500         0
4   35.0  male  Third   8.0500         0
5    NaN  male  Third   8.4583         0
7    2.0  male  Third  21.0750         0
12  20.0  male  Third   8.0500         0

In [8]:
average_two = grouped_two.mean(numeric_only=True)
average_two

                     age        fare  survived
class  sex
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

In [9]:
group3f = grouped_two.get_group(('Third','female'))
group3f.head()

     age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

In [10]:
grouped

In [11]:
std_all = grouped.std(numeric_only=True)
std_all

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [12]:
std_all_index = df.groupby(['class'],observed=True, as_index=False).std(numeric_only=True)
std_all_index

    class        age       fare  survived
0   First  14.802856  78.380373  0.484026
1  Second  14.001077  13.417399  0.500623
2   Third  12.495398  11.778142  0.428949

In [13]:
std_all['fare']

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [14]:
std_fare = grouped['fare'].std(numeric_only=True)
std_fare

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [16]:
std_age_survived = grouped[['age', 'survived']].std(numeric_only=True)
std_age_survived

              age  survived
class
First   14.802856  0.484026
Second  14.001077  0.500623
Third   12.495398  0.428949

In [17]:
grouped.describe()

          age                                                       fare  \
        count       mean        std   min   25%   50%   75%   max  count
class
First   186.0  38.233441  14.802856  0.92  27.0  37.0  49.0  80.0  216.0
Second  173.0  29.877630  14.001077  0.67  23.0  29.0  36.0  70.0  184.0
Third   355.0  25.140620  12.495398  0.42  18.0  24.0  32.0  74.0  491.0

                   ...                 survived                                \
             mean  ...   75%       max    count      mean       std  min  25%
class              ...
First   84.154687  ...  93.5  512.3292    216.0  0.629630  0.484026  0.0  0.0
Second  20.662183  ...  26.0   73.5000    184.0  0.472826  0.500623  0.0  0.0
Third   13.675550  ...  15.5   69.5500    491.0  0.242363  0.428949  0.0  0.0


        50%  75%  max
class
First   1.0  1.0  1.0
Second  0.0  1.0  1.0
Third   0.0  0.0  1.0

[3 rows x 24 columns]

In [18]:
grouped[['class','sex']].value_counts()

class   sex
First   male      122
        female     94
Second  male      108
        female     76
Third   male      347
        female    144
Name: count, dtype: int64

In [19]:
agg_mean = grouped.aggregate('mean',numeric_only=True)
agg_mean

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [20]:
agg_mean2 = grouped.agg('mean',numeric_only=True)
agg_mean2

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [21]:
agg_all = grouped.agg(['min','max'])
agg_all

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [22]:
agg_sep = grouped.agg({
    'fare':['min','max'],
    'age':'mean'
})

agg_sep

       fare                  age
        min       max       mean
class
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620

In [23]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [24]:
def min_max(x):
    return x.max() - x.min()

agg_minmax = grouped[['age','fare']].agg(min_max)

agg_minmax

          age      fare
class
First   79.08  512.3292
Second  69.33   73.5000
Third   73.58   69.5500

In [27]:
df

      age     sex   class     fare  survived
0    22.0    male   Third   7.2500         0
1    38.0  female   First  71.2833         1
2    26.0  female   Third   7.9250         1
3    35.0  female   First  53.1000         1
4    35.0    male   Third   8.0500         0
..    ...     ...     ...      ...       ...
886  27.0    male  Second  13.0000         0
887  19.0  female   First  30.0000         1
888   NaN  female   Third  23.4500         0
889  26.0    male   First  30.0000         1
890  32.0    male   Third   7.7500         0

[891 rows x 5 columns]

In [28]:
grouped = df.groupby(['class'],observed=True)

grouped['fare'].cumsum()

0          7.2500
1         71.2833
2         15.1750
3        124.3833
4         23.2250
          ...
886     3801.8417
887    18147.4125
888     6706.9451
889    18177.4125
890     6714.6951
Name: fare, Length: 891, dtype: float64

In [29]:
df['fare_cumsum'] = grouped['fare'].cumsum()
df.head()

    age     sex  class     fare  survived  fare_cumsum
0  22.0    male  Third   7.2500         0       7.2500
1  38.0  female  First  71.2833         1      71.2833
2  26.0  female  Third   7.9250         1      15.1750
3  35.0  female  First  53.1000         1     124.3833
4  35.0    male  Third   8.0500         0      23.2250

In [34]:
grouped[['fare']].transform('cumsum')

           fare
0        7.2500
1       71.2833
2       15.1750
3      124.3833
4       23.2250
..          ...
886   3801.8417
887  18147.4125
888   6706.9451
889  18177.4125
890   6714.6951

[891 rows x 1 columns]

In [35]:
grouped[['age','survived']].transform('mean')

           age  survived
0    25.140620  0.242363
1    38.233441  0.629630
2    25.140620  0.242363
3    38.233441  0.629630
4    25.140620  0.242363
..         ...       ...
886  29.877630  0.472826
887  38.233441  0.629630
888  25.140620  0.242363
889  38.233441  0.629630
890  25.140620  0.242363

[891 rows x 2 columns]

In [36]:
def z_score(x):
    return (x - x.mean()) / x.std()

age_zscore = grouped['age'].transform(z_score)
age_zscore

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64

In [37]:
age_zscore2 = grouped['age'].transform(lambda x: (x - x.mean()) / x.std())
age_zscore2

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64

In [38]:
age_zscore3 = (df['age'] - grouped['age'].transform('mean')) / grouped['age'].transform('std')
age_zscore3

0     -0.251342
1     -0.015770
2      0.068776
3     -0.218434
4      0.789041
         ...
886   -0.205529
887   -1.299306
888         NaN
889   -0.826424
890    0.548953
Name: age, Length: 891, dtype: float64

In [39]:
grouped = df.groupby(['class'], observed=True)

grouped_head = grouped.head(2)
grouped_head

     age     sex   class     fare  survived  fare_cumsum
0   22.0    male   Third   7.2500         0       7.2500
1   38.0  female   First  71.2833         1      71.2833
2   26.0  female   Third   7.9250         1      15.1750
3   35.0  female   First  53.1000         1     124.3833
9   14.0  female  Second  30.0708         1      30.0708
15  55.0  female  Second  16.0000         1      46.0708

In [40]:
grouped_first = grouped.nth(1)
grouped_first

     age     sex   class    fare  survived  fare_cumsum
2   26.0  female   Third   7.925         1      15.1750
3   35.0  female   First  53.100         1     124.3833
15  55.0  female  Second  16.000         1      46.0708

In [41]:
grouped[['sex','survived']].nth(1)

       sex  survived
2   female         1
3   female         1
15  female         1

In [42]:
grouped_filter = grouped.filter(lambda x: len(x) >= 200)
grouped_filter

      age     sex  class     fare  survived  fare_cumsum
0    22.0    male  Third   7.2500         0       7.2500
1    38.0  female  First  71.2833         1      71.2833
2    26.0  female  Third   7.9250         1      15.1750
3    35.0  female  First  53.1000         1     124.3833
4    35.0    male  Third   8.0500         0      23.2250
..    ...     ...    ...      ...       ...          ...
885  39.0  female  Third  29.1250         0    6683.4951
887  19.0  female  First  30.0000         1   18147.4125
888   NaN  female  Third  23.4500         0    6706.9451
889  26.0    male  First  30.0000         1   18177.4125
890  32.0    male  Third   7.7500         0    6714.6951

[707 rows x 6 columns]

In [46]:
age_filter = grouped.filter( lambda x: x['age'].mean() < 30)
age_filter

      age     sex   class     fare  survived  fare_cumsum
0    22.0    male   Third   7.2500         0       7.2500
2    26.0  female   Third   7.9250         1      15.1750
4    35.0    male   Third   8.0500         0      23.2250
5     NaN    male   Third   8.4583         0      31.6833
7     2.0    male   Third  21.0750         0      52.7583
..    ...     ...     ...      ...       ...          ...
884  25.0    male   Third   7.0500         0    6654.3701
885  39.0  female   Third  29.1250         0    6683.4951
886  27.0    male  Second  13.0000         0    3801.8417
888   NaN  female   Third  23.4500         0    6706.9451
890  32.0    male   Third   7.7500         0    6714.6951

[675 rows x 6 columns]

In [47]:
grouped

In [50]:
agg_grouped = grouped[['age','survived']].apply(lambda x: x.describe())
agg_grouped.round(2)

                 age  survived
class
First  count  186.00    216.00
       mean    38.23      0.63
       std     14.80      0.48
       min      0.92      0.00
       25%     27.00      0.00
       50%     37.00      1.00
       75%     49.00      1.00
       max     80.00      1.00
Second count  173.00    184.00
       mean    29.88      0.47
       std     14.00      0.50
       min      0.67      0.00
       25%     23.00      0.00
       50%     29.00      0.00
       75%     36.00      1.00
       max     70.00      1.00
Third  count  355.00    491.00
       mean    25.14      0.24
       std     12.50      0.43
       min      0.42      0.00
       25%     18.00      0.00
       50%     24.00      0.00
       75%     32.00      0.00
       max     74.00      1.00

In [51]:
def z_score(x):
    return (x - x.mean()) / x.std()

age_zscore = grouped[['age','survived']].apply(z_score)
age_zscore

                age  survived
class
First 1   -0.015770  0.765188
      3   -0.218434  0.765188
      6    1.065103 -1.300819
      11   1.335321  0.765188
      23  -0.691315  0.765188
...             ...       ...
Third 882 -0.251342 -0.565014
      884 -0.011254 -0.565014
      885  1.109159 -0.565014
      888       NaN -0.565014
      890  0.548953 -0.565014

[891 rows x 2 columns]

In [52]:
age_filter = grouped[['age','survived']].apply(lambda x: x['age'].mean() < 30)
print(age_filter, '\n')

df.loc[df['class'].isin(age_filter[age_filter==True].index), ['age','survived']]

class
First     False
Second     True
Third      True
dtype: bool

      age  survived
0    22.0         0
2    26.0         1
4    35.0         0
5     NaN         0
7     2.0         0
..    ...       ...
884  25.0         0
885  39.0         0
886  27.0         0
888   NaN         0
890  32.0         0

[675 rows x 2 columns]