In [1]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','sex','class','fare','survived']]

grouped = df.groupby(['sex','class'],observed=True)

gdf = grouped.agg(['mean',"std"],numeric_only=True)

gdf

                     age                   fare             survived
                    mean        std        mean        std      mean       std
sex    class
female First   34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
       Second  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       Third   21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
male   First   41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
       Second  30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       Third   26.507589  12.159514   12.661633  11.681696  0.135447  0.342694

In [2]:
gdf.index

MultiIndex([('female',  'First'),
            ('female', 'Second'),
            ('female',  'Third'),
            (  'male',  'First'),
            (  'male', 'Second'),
            (  'male',  'Third')],
           names=['sex', 'class'])

In [3]:
arrays = [
    ['a','a','b','b'],
    [1,2,1,2]
]

multi_index_arrays = pd.MultiIndex.from_arrays(arrays,names=('letter','number'))
multi_index_arrays

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [4]:
tuples = [
    ('a',1),
    ('a',2),
    ('b',1),
    ('b',2)
]

multi_index_tuples = pd.MultiIndex.from_tuples(tuples,names=('letter','number'))
multi_index_tuples

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [5]:
letters = ['a','b']
numbers = [1,2]

multi_index_prodect = pd.MultiIndex.from_product([letters,numbers],names=('letter','number'))

multi_index_prodect

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [6]:
df = pd.DataFrame([['a',1],['a',2],['b',1],['b',2]],columns=['letter','number'])
multi_index_frame = pd.MultiIndex.from_frame(df)
multi_index_frame

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['letter', 'number'])

In [7]:
multi_index_frame.get_level_values(0)

Index(['a', 'a', 'b', 'b'], dtype='str', name='letter')

In [8]:
multi_index_frame.get_level_values('letter')

Index(['a', 'a', 'b', 'b'], dtype='str', name='letter')

In [10]:
gdf

                     age                   fare             survived
                    mean        std        mean        std      mean       std
sex    class
female First   34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
       Second  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       Third   21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
male   First   41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
       Second  30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       Third   26.507589  12.159514   12.661633  11.681696  0.135447  0.342694

In [9]:
gdf.columns.levels

FrozenList([['age', 'fare', 'survived'], ['mean', 'std']])

In [11]:
gdf.columns.get_level_values(0)

Index(['age', 'age', 'fare', 'fare', 'survived', 'survived'], dtype='str')

In [12]:
gdf['age']

                    mean        std
sex    class
female First   34.611765  13.612052
       Second  28.722973  12.872702
       Third   21.750000  12.729964
male   First   41.281386  15.139570
       Second  30.740707  14.793894
       Third   26.507589  12.159514

In [13]:
gdf['age','mean']

sex     class
female  First     34.611765
        Second    28.722973
        Third     21.750000
male    First     41.281386
        Second    30.740707
        Third     26.507589
Name: (age, mean), dtype: float64

In [14]:
gdf['age']['mean']

sex     class
female  First     34.611765
        Second    28.722973
        Third     21.750000
male    First     41.281386
        Second    30.740707
        Third     26.507589
Name: mean, dtype: float64

In [30]:
gdf.xs('male',level='sex')

              age                  fare             survived
             mean        std       mean        std      mean       std
class
First   41.281386  15.139570  67.226127  77.548021  0.368852  0.484484
Second  30.740707  14.793894  19.741782  14.922235  0.157407  0.365882
Third   26.507589  12.159514  12.661633  11.681696  0.135447  0.342694

In [31]:
gdf.sort_index(level=0,ascending=False)

                     age                   fare             survived
                    mean        std        mean        std      mean       std
sex    class
male   Third   26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
       Second  30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       First   41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
female Third   21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
       Second  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       First   34.611765  13.612052  106.125798  74.259988  0.968085  0.176716

In [32]:
gdf.sort_index(level='sex',ascending=False)

                     age                   fare             survived
                    mean        std        mean        std      mean       std
sex    class
male   Third   26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
       Second  30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       First   41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
female Third   21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
       Second  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       First   34.611765  13.612052  106.125798  74.259988  0.968085  0.176716

In [33]:
gdf.sort_index(level=['sex','class'],ascending=[False,True])

                     age                   fare             survived
                    mean        std        mean        std      mean       std
sex    class
male   First   41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
       Second  30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       Third   26.507589  12.159514   12.661633  11.681696  0.135447  0.342694
female First   34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
       Second  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       Third   21.750000  12.729964   16.118810  11.690314  0.500000  0.501745

In [43]:
gdf.iloc[0]

age       mean     34.611765
          std      13.612052
fare      mean    106.125798
          std      74.259988
survived  mean      0.968085
          std       0.176716
Name: (female, First), dtype: float64

In [39]:
gdf

                     age                   fare             survived
                    mean        std        mean        std      mean       std
sex    class
female First   34.611765  13.612052  106.125798  74.259988  0.968085  0.176716
       Second  28.722973  12.872702   21.970121  10.891796  0.921053  0.271448
       Third   21.750000  12.729964   16.118810  11.690314  0.500000  0.501745
male   First   41.281386  15.139570   67.226127  77.548021  0.368852  0.484484
       Second  30.740707  14.793894   19.741782  14.922235  0.157407  0.365882
       Third   26.507589  12.159514   12.661633  11.681696  0.135447  0.342694