In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["John", "Mary"],
    "City": ["New York", "Los Angeles"],
    "Age": [28, 32],
    "Salary": [50000, 60000],
})

df

   Name         City  Age  Salary
0  John     New York   28   50000
1  Mary  Los Angeles   32   60000

In [3]:
df_melted = df.melt(id_vars=["Name", "City"], 
                    var_name="Attribute", 
                    value_name="Value")

df_melted

   Name         City Attribute  Value
0  John     New York       Age     28
1  Mary  Los Angeles       Age     32
2  John     New York    Salary  50000
3  Mary  Los Angeles    Salary  60000

In [4]:
df_wide = pd.DataFrame({
    "Company": ["Google", "Yahoo"],
    "Income_2019": [100000, 50000],
    "Income_2020": [120000, 55000],
    "Expense_2019": [50000, 30000],
    "Expense_2020": [60000, 35000]
})

df_wide

  Company  Income_2019  Income_2020  Expense_2019  Expense_2020
0  Google       100000       120000         50000         60000
1   Yahoo        50000        55000         30000         35000

In [5]:
df_long = pd.wide_to_long(df_wide, stubnames=['Income', 'Expense'], 
                          i='Company', j='Year', sep='_', suffix='\d+')
df_long = df_long.reset_index()
df_long

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\KDS23\AppData\Local\Temp\ipykernel_17792\3823085536.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  i='Company', j='Year', sep='_', suffix='\d+')

  Company  Year  Income  Expense
0  Google  2019  100000    50000
1   Yahoo  2019   50000    30000
2  Google  2020  120000    60000
3   Yahoo  2020   55000    35000