In [1]:
import pandas as pd

import numpy as np

In [7]:
df = pd.read_csv("./data/auto-mpg.csv",header=None)

df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year', 'origin','name']

df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [8]:
df['horsepower'] = df['horsepower'].replace('?',np.nan)
df = df.dropna(subset=['horsepower'],axis=0)
df['horsepower'] = df['horsepower'].astype('float')

In [9]:
count,bin_dividers = np.histogram(df['horsepower'], bins=3)
print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]

In [10]:
bin_names = ['저출력','보통출력','고출력']

df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins=bin_dividers,
                      labels=bin_names,
                      include_lowest=True)

df[['horsepower','hp_bin']].head(15)

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

In [11]:
count, bin_dividers = np.histogram(df['horsepower'],bins=3)

bin_names = ['저출력','보통출력','고출력']

df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins=bin_dividers,
                      labels=bin_names,
                      include_lowest=True)

horsepower_dummies = pd.get_dummies(df['hp_bin'])
print(horsepower_dummies)

       저출력   보통출력    고출력
0    False   True  False
1    False   True  False
2    False   True  False
3    False   True  False
4    False   True  False
..     ...    ...    ...
393   True  False  False
394   True  False  False
395   True  False  False
396   True  False  False
397   True  False  False

[392 rows x 3 columns]

In [12]:
horsepower_dummies_float = pd.get_dummies(df['hp_bin'],dtype=float)
horsepower_dummies_float.head()

   저출력  보통출력  고출력
0  0.0   1.0  0.0
1  0.0   1.0  0.0
2  0.0   1.0  0.0
3  0.0   1.0  0.0
4  0.0   1.0  0.0

In [14]:
horsepower_dummies_drop = pd.get_dummies(df['hp_bin'],dtype=float,drop_first=True)
horsepower_dummies_drop.head()

   보통출력  고출력
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   1.0  0.0

In [16]:
from sklearn import preprocessing

In [23]:
label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df['hp_bin'].head(15))
print(onehot_labeled)
print('\n')
print(type(onehot_labeled))
print('\n')

onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled),1)
print(onehot_reshaped)
print('\n')
print(type(onehot_reshaped))
print('\n')

onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print('\n')
print(type(onehot_fitted))

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]


<class 'numpy.ndarray'>


[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]


<class 'numpy.ndarray'>


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0


<class 'scipy.sparse._csr.csr_matrix'>